INSERT INTO tb_continent (name,language) values ('Ásia',0);
INSERT INTO tb_continent (name,language) values ('África',0);
INSERT INTO tb_continent (name,language) values ('Oriente Médio e Egito',0);
INSERT INTO tb_continent (name,language) values ('América Latina',0);
INSERT INTO tb_continent (name,language) VALUES ('Europa',0);
INSERT INTO tb_continent (name,language) VALUES ('Oceania',0);
INSERT INTO tb_continent (name,language) VALUES ('América do Norte',0);
INSERT INTO tb_continent (name,language) VALUES ('Antártica',0);

INSERT INTO tb_country (name,language,continent_id) VALUES ('Austrália',0,6);
INSERT INTO tb_country (name,language,continent_id) VALUES ('New Zealand',0,6);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Fiji',0,6);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Tahiti',0,6);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Egito',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Jordânia',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Israel',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Turquia',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Iran',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('França',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Bulgária',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Romênia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('República Checa',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Hungria',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Polônia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Argentina',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Chile',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Equador',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Peru',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Bolívia',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Costa Rica',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Honduras',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Guatemala',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('México',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Quênia',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Tanzânia',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Uganda',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Seychelles',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Namíbia',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Botswana',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Zimbabwe',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('África do Sul',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Mauritius',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Mali',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Níger',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Marrocos',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Tunísia',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Uzbekistan',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Kazakhistan',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Paquistão',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Índia',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Sri Lanka',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Maldivas',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Nepal',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Tibet',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('China',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Mongólia',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Myanmar',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Butão',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Laos',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Vietnã',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Cambodja',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Tailândia',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Malásia',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Indonésia',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Quirguistan',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Brasil',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Russia',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Cingapura',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Inglaterra',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Emirados Árabes Unidos',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Oman',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Espanha',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Rwanda',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Itália',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Portugal',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Alemanha',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Grécia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Síria',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Brunei',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Estados Unidos',0,7);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Holanda',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Armênia',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Eslovênia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Croácia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Eslováquia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Suiça',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Coréia do Sul',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Taiwan',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Antárctica',0,8);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Madagascar',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Japão',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Etiópia',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Moçambique',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Hong Kong',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Burkina Faso',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Cape Verde',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Senegal',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Moldavia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Bélgica',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Azerbaijão',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Ucrânia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Moldávia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Geórgia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Croácia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Tajiquistão',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Turcomenistão',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Servia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Bosnia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Herzegovina',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Montenegro',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Bangladesh',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Uruguai',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Austria',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Malawi',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Libano',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Qatar',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Escócia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Austria',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Suécia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Irlanda Norte',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Irlanda Sul',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Finlândia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Islandia',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Canada',0,7);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Papua Nova Guiné',0,6);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Venezuela',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Colombia',0,4);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Noruega',0,5);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Armênia',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Geórgia',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Azerbaijão',0,3);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Filipinas',0,1);
INSERT INTO tb_country (name,language,continent_id) VALUES ('I. Canárias',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('I. Madeiras',0,2);
INSERT INTO tb_country (name,language,continent_id) VALUES ('Arábia Saudita',0,3);

INSERT INTO tb_expedition (title,photo,link_h,intro_text,country_id,title_extra,show_country,publish,link_on_off,im_w,im_h,hide_date_operator,hide_date,duration,date,creation_date,conditions) VALUES ('Nuno Alves prog 1','Botswana-sum-site.jpg', 0,'<br><b>BOTSWANA</b><br><br>Quando presa e predador bebem água lado a lado, há algo de diferente no ar. Talvez seja porque, num capricho da natureza, todo o delta de um rio desaparece em meio ao nada. Talvez seja apenas sede.',30,1,1,0,0,250,243,0,0,18,'2025-12-01','2025-11-10',0);

INSERT INTO tb_expedition_country (expedition_id,country_id,icon_elephant,icon_canoe,icon_beach,icon_jeep,icon_jeep2,icon_mountain,icon_boat,icon_train,icon_trekking,icon_scuba,icon_bike,icon_bus,icon_selo) VALUES (1,30,1,1,1,1,1,1,1,1,1,1,1,1,1);
INSERT INTO tb_expedition_country (expedition_id,country_id,icon_elephant,icon_canoe,icon_beach,icon_jeep,icon_jeep2,icon_mountain,icon_boat,icon_train,icon_trekking,icon_scuba,icon_bike,icon_bus,icon_selo) VALUES (1,31,1,1,1,1,1,1,1,1,1,1,1,1,1);
INSERT INTO tb_expedition_country (expedition_id,country_id,icon_elephant,icon_canoe,icon_beach,icon_jeep,icon_jeep2,icon_mountain,icon_boat,icon_train,icon_trekking,icon_scuba,icon_bike,icon_bus,icon_selo) VALUES (1,84,1,1,1,1,1,1,1,1,1,1,1,1,1);